### ISSUE TITLE
No need to clone options

### ISSUE THREAD

**Issue by domenic** [lukechilds/window#11]
https://github.com/lukechilds/window/blob/4156146ad0f9f6c765e1cde48df6cf1fc1ec826b/src/index.js#L7-L8 claims that jsdom mutates the passed-in options object, but that is not true. I just added a test to jsdom to confirm and ensure this stays the case going forward: https://github.com/tmpvar/jsdom/pull/2035

**Comment by lukechilds** [comment]
Thanks for letting me know, I think that was the case when I initially wrote this, great that it's resolved and tested now.

Pretty swamped with paid work atm but will get this done as soon as I can.
