### ISSUE TITLE
Remove 'use strict';

### ISSUE THREAD

**Issue by lukechilds** [lukechilds/window#12]
We only support Node.js 6 and up now so strict mode is implied (I think, check this).

**Comment by TehShrike** [comment]
strict mode is only on by default in ES modules, I believe.

**Comment by lukechilds** [comment]
@TehShrike thanks, looks like classes are too:

> All parts of a ClassDeclaration or a ClassExpression are strict mode code.

http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code

Running a build now, if it passes I'll merge.
