### ISSUE TITLE
Update jsdom

### ISSUE THREAD

**Issue by OmgImAlexis** [lukechilds/window#3]
According to the jsdom issue template they only support v10+ now and this package is still on `9.11.0`

**Comment by lukechilds** [comment]
Sorry I slipped behind on updates due to GreenKeeper randomly stopping working.

Re-enabled it the other day and realised there were some breaking changes. I've been busy with another project and didn't have time to work on a fix. I'll try and get this sorted ASAP.

**Comment by lukechilds** [comment]
@OmgImAlexis Done.

Published as SemVer major due to jsdom no longer supporting Node.js versions below 6.
