### ISSUE TITLE
npm security fix needed: update jsdom

### ISSUE THREAD

**Issue by createthis** [lukechilds/window#38]
See https://www.npmjs.com/advisories/1488
<img width="904" alt="Screen Shot 2020-03-09 at 2 42 06 PM" src="https://user-images.githubusercontent.com/1695880/76246476-2c47ea80-6214-11ea-99a2-aae1ad23e8cb.png">

**Comment by createthis** [comment]
@lukechilds ping

**Comment by lukechilds** [comment]
@createthis thanks, fixed in https://github.com/lukechilds/window/commit/134ecc93a0941176e209107ea3cf7eb6c5cf72de.

Published as `window@4.2.7`.
